server:
  port: 9005

spring:
  application:
    name: sleuth-service
  zipkin:
    base-url: http://localhost:9441
    sleuth:
      sampler:
        probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
