server:
  port: 7003

spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/morning97star/springcloud-config-test.git
          search-paths: springcloud-config-test
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
