server:
  port: 7005

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: route1
          uri: lb://payment-service
          predicates:
            - Path=/payment/get/**
#        - id: route2
#          uri: lb://payment-service
#          predicates:
#            - PATH=/payment/hello
      discovery:
        locator:
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka